name: Compile & Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Run unit tests
        run: go test -v -count=1 -failfast ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
          args: --config=build/ci/.golangci.yml
